name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Debug(1)
      run: pwd

    - name: Checkout uhppote-core
      run: git clone https://github.com/uhppoted/uhppote-core.git
  
    - name: Checkout uhppoted-api
      run: git clone https://github.com/uhppoted/uhppoted-api.git
      
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Debug(2)
      run: pwd
      
    - name: Debug(3)
      run: ls -1 ..
        
    - name: Build
      run: make release
      
